[package]
name = "gamma-chess"
version = "0.0.0"
license = "MIT"
edition = "2021"

[dependencies]

ggez = "0.9.0-rc0"
map-macro = "0.2.6"
ggegui = { git = "https://github.com/the-jasoney/ggegui-0.9.0-rc0.git" }
